[target.x86_64-unknown-uefi]
runner = ["uefi/script/boot.sh", "x86-64"]

[target.i686-unknown-uefi]
runner = ["uefi/script/boot.sh", "x86"]
# rustflags = ["-C", "linker-flag="]

[target.thumbv7a-unknown-uefi]
runner = ["uefi/script/boot.sh", "arm"]

[target.aarch64-unknown-uefi]
runner = ["uefi/script/boot.sh", "arm64"]
