[alias]
"test-host" = "test -Z build-std=core,alloc,std --target x86_64-apple-darwin"
"clippy-test-host" = "clippy --tests -Z build-std=core,alloc,std --target x86_64-apple-darwin"

[build]
target = "x86_64-unknown-uefi"

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-arg=-lSystem"]

[target.x86_64-unknown-uefi]
runner = "script/boot.sh"
# Fix an error compiling the memchr crate with the default x86_64-unknown-uefi settings:
#   https://github.com/rust-lang/rust/issues/61721
# TODO: The default setting enables soft floats and disables MMX/SSE because those
# instruction sets need explicit initialization. We need to perform that initialization
# if the firmware doesn't.
rustflags = ["-C", "target-feature=-soft-float"]

[unstable]
build-std = ["core", "alloc"]
