[unstable]
extra-link-arg = true

[target.x86_64-unknown-uefi]
runner = ["uefi/script/boot.sh", "x86_64"]

[target.i686-unknown-uefi]
runner = ["uefi/script/boot.sh", "i686"]

[target.arm-unknown-uefi]
runner = ["uefi/script/boot.sh", "arm"]

[target.aarch64-unknown-uefi]
runner = ["uefi/script/boot.sh", "aarch64"]
