[alias]
"test-host" = "test -Z build-std=core,alloc,std --target x86_64-apple-darwin"
"clippy-test-host" = "clippy --tests -Z build-std=core,alloc,std --target x86_64-apple-darwin"

[build]
target = "x86_64-unknown-uefi"

[target.x86_64-unknown-uefi]
runner = "script/boot.sh"

[unstable]
build-std = ["core", "alloc"]
