# Settings required for cross-compiling for UEFI. These are only used by Cargo if you run
# it from within the uefi/ directory.

[build]
target = "x86_64-unknown-uefi"
# Work around an issue compiling memchr 2.2+ with soft floats enabled
# https://github.com/rust-lang/rust/issues/61721
# https://github.com/BurntSushi/rust-memchr/blob/378bb1caecac7079b867fa6e6059c0d8ea244e03/build.rs#L8
rustflags = ["--cfg", "memchr_disable_auto_simd"]
# rustflags = ["-C", "target-feature=-sse,-sse2,-sse3,-sse4.1,-sse4.2,-sse4a,-ssse3"]

[unstable]
build-std = ["core", "alloc", "std"]
build-std-features = []
