[package]
name = "tartan-bitfield"
version = "0.1.0"
authors = ["Tim Yates <cimbul@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/cimbul/tartan-os"
publish = false

[dependencies]
paste = "1.0.0"

[dev-dependencies]
criterion = "0.3.3"
criterion-macro = "0.3.3"
