#![warn(clippy::pedantic)]

use insta::{assert_debug_snapshot, glob, with_settings};
use std::fs;
use tartan_acpi::aml::parse::parse_table;

#[test]
fn parse_all() {
    // Parse all AML files and compare to past output
    glob!("aml/*.aml", |aml_path| {
        // Make the autogenerated snapshot filenames less wordy
        let test_name = aml_path.file_stem().unwrap().to_str().unwrap();
        with_settings!({snapshot_suffix => ""}, {
            let aml_data = fs::read(aml_path).unwrap();
            assert_debug_snapshot!(test_name, parse_table(&aml_data));
        });
    });
}
