name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install components
      run: rustup component add rust-src rustfmt clippy
    - name: Format
      run: cargo fmt --all -- --check
    - name: Lint
      run: cargo clippy --workspace --all-targets -- -D warnings
    - name: Document
      run: |
        cargo doc --workspace --no-deps
        cp doc/crate-redirect.html target/doc/index.html
    - name: Build (Linux)
      run: cargo build --verbose --workspace
    - name: Run tests (Linux)
      run: cargo test --verbose --workspace
		- name: Build (UEFI x86)
			run: (cd uefi && cargo build --target target-specs/i686-unknown-uefi.json)
    - name: Build (UEFI x86-64)
			run: (cd uefi && cargo build --target target-specs/x86_64-unknown-uefi.json)
		- name: Build (UEFI arm)
			run: (cd uefi && cargo build --target target-specs/thumbv7a-unknown-uefi.json)
		- name: Build (UEFI arm64)
			run: (cd uefi && cargo build --target target-specs/aarch64-unknown-uefi.json)
    - name: GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.6.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/doc/
        cname: tartan.cimbul.com
