name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install components
      run: rustup component add rust-src rustfmt clippy
    - name: Format
      run: cargo fmt --all -- --check
    - name: Lint
      run: cargo clippy --workspace --all-targets -- -D warnings
    - name: Document
      run: cargo doc --workspace --no-deps
    - name: Build (Linux)
      run: cargo build --verbose --workspace
    - name: Run tests (Linux)
      run: cargo test --verbose --workspace
    - name: Build (UEFI)
      run: (cd uefi && cargo build)
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.2
      with:
        # Build directory to deploy
        build_dir: target/doc
        jekyll: false
