name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      uses: hecrj/setup-rust-action@v1.3.3
      with:
        rust-version: nightly
        components: rustfmt, clippy, rustdoc
        targets: x86_64-unknown-linux-gnu, x86_64-unknown-uefi
    - name: Format
      run: cargo fmt --all -- --check
    - name: Lint
      run: cargo clippy --workspace --all-targets -- -D warnings
    - name: Document
      run: cargo doc --document-private-items
    - name: Build (Linux)
      run: cargo build --verbose --workspace
    - name: Run tests (Linux)
      run: cargo test --verbose --workspace
    - name: Build (UEFI)
      run: (cd uefi && cargo build)
